# Generated by Django 6.0.8 on 2026-08-19 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_appearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_characters', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='novels.novel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('evidence_reference', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_developments', to='novels.chapter')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='story.character')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_developments', to='novels.novel')),
            ],
            options={
                'ordering': ['chapter__chapter_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_detected_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_first_seen', to='novels.chapter')),
                ('last_updated_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_last_seen', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='novels.novel')),
                ('source_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='story.character')),
                ('target_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='story.character')),
            ],
            options={
                'ordering': ['source_character__name'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('object', 'Object'), ('setting_detail', 'Setting'), ('character_detail', 'Character'), ('historical_context', 'Historical context'), ('conversation_detail', 'Conversation'), ('symbol', 'Symbol'), ('motif', 'Motif'), ('foreshadowing', 'Foreshadowing'), ('plot', 'Plot'), ('relationship', 'Relationship'), ('emotional', 'Emotional'), ('other', 'Other')], default='other', max_length=40)),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('minor', 'Minor')], default='minor', max_length=20)),
                ('evidence_reference', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_details', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_details', to='novels.novel')),
            ],
            options={
                'ordering': ['chapter__chapter_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('first_appearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_locations', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='novels.novel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('conversation', 'Conversation'), ('conflict', 'Conflict'), ('revelation', 'Revelation'), ('decision', 'Decision'), ('relationship_change', 'Relationship change'), ('travel', 'Travel'), ('death', 'Death'), ('discovery', 'Discovery'), ('emotional_change', 'Emotional change'), ('introduction', 'Introduction'), ('other', 'Other')], default='other', max_length=40)),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('minor', 'Minor')], default='important', max_length=20)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('evidence_reference', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='novels.chapter')),
                ('characters_involved', models.ManyToManyField(blank=True, related_name='events', to='story.character')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='novels.novel')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='story.location')),
            ],
            options={
                'ordering': ['chapter__chapter_number', 'sequence_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('evidence_reference', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_states', to='novels.chapter')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='story.characterrelationship')),
            ],
            options={
                'ordering': ['chapter__chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='ThemeMotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('evidence_reference', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='novels.novel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('novel', 'name'), name='unique_character_name_per_novel'),
        ),
        migrations.AddConstraint(
            model_name='characterrelationship',
            constraint=models.UniqueConstraint(fields=('novel', 'source_character', 'target_character', 'relationship_type'), name='unique_relationship_edge'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('novel', 'name'), name='unique_location_name_per_novel'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['novel', 'chapter'], name='story_event_novel_i_d86df1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'importance'], name='story_event_event_t_687038_idx'),
        ),
        migrations.AddConstraint(
            model_name='relationshipstate',
            constraint=models.UniqueConstraint(fields=('relationship', 'chapter'), name='unique_relationship_state_per_chapter'),
        ),
    ]
