# Generated by Django 6.0.8 on 2026-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
