# Generated by Django 6.0.8 on 2026-08-19 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('reading_status', models.CharField(choices=[('not_started', 'Not started'), ('reading', 'Reading'), ('paused', 'Paused'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('current_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_markers', to='novels.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'novel'), name='unique_progress_per_user_novel')],
            },
        ),
        migrations.CreateModel(
            name='Recap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_chapter', models.PositiveIntegerField()),
                ('to_chapter', models.PositiveIntegerField()),
                ('recap_type', models.CharField(choices=[('quick_30', '30-second recap'), ('standard_2min', '2-minute recap'), ('detailed_5min', '5-minute recap')], max_length=20)),
                ('content', models.TextField()),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_updated_at', models.DateTimeField(help_text='Latest chapter updated_at at generation time; used to invalidate cache.')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaps', to='novels.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'novel', 'from_chapter', 'to_chapter', 'recap_type'], name='reading_rec_user_id_c39502_idx')],
            },
        ),
    ]
